--- #YAML:1.0
name: Test-NoBreakpoints
version: 0.11
author:
  - James FitzGibbon E<lt>jfitz@CPAN.orgE<gt>
abstract: test that files do not contain soft breakpoints
license: perl
requires:
  Test::Builder: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Tester: 0
provides:
  Test::NoBreakpoints:
    file: lib/Test/NoBreakpoints.pm
    version: 0.11
generated_by: Module::Build version 0.2607
